AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

plugins:
  - rubocop-rake
  - rubocop-rspec

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - spec/ansi_shadow_spec.rb

RSpec/ExampleLength:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true
